title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    header: 新生报到
    content:
      - text: 大学第一天
        path: /guide/check/first-day

  - tag: grid
    header: 最常访问
    content:
      - text: 入学课程
        color: red
        name: Course
        icon: /icon/guide/study.svg
        base64Icon: study
        path: /guide/prepare/yiban/

      - text: 新生报到
        color: orange
        name: Check
        icon: /icon/guide/check.svg
        base64Icon: check
        path: /guide/check/

      - text: 入学活动
        color: blue
        name: Activity
        icon: https://mp.innenu.com/img/icon/guide/activity.svg
        base64Icon: activity
        path: guide/activity/

      - text: 校园卡
        color: purple
        name: Card
        icon: /icon/guide/card.svg
        base64Icon: card
        path: /guide/card/

      - text: 寝室
        color: mauve
        name: Dorm
        icon: /icon/guide/dorm.svg
        base64Icon: dorm
        path: /guide/dorm/

      - text: 食堂
        color: olive
        name: Dining
        icon: /icon/guide/dining.svg
        base64Icon: dining
        path: /guide/dining/

      - text: 校园网
        color: red
        name: Network
        icon: /icon/guide/network.svg
        base64Icon: network
        path: /guide/network/

      - text: 快递
        color: blue
        name: blue
        icon: https://mp.innenu.com/img/icon/guide/express.svg
        base64Icon: express
        path: /guide/express/

      - text: 超市
        color: orange
        name: Shop
        icon: https://mp.innenu.com/img/icon/guide/shop.svg
        base64Icon: shop
        path: /guide/shop/

      - text: 洗浴
        color: purple
        name: Bath
        icon: https://mp.innenu.com/img/icon/guide/bath.svg
        base64Icon: bath
        path: guide/bath/

      - text: 账户
        color: olive
        name: Account
        icon: /icon/guide/account.svg
        base64Icon: account
        path: guide/account/
