title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    content:
      - text: 大学第一天
        path: /guide/prepare/first-day

  - tag: grid
    header: 最常访问
    content:
      - text: 入学课程
        color: red
        name: Course
        icon: /icon/guide/study.svg
        path: /guide/prepare/yiban/

      - text: 入学准备
        color: orange
        name: Prepare
        icon: /icon/guide/prepare.svg
        path: /guide/prepare/

      - text: 需带物品
        color: blue
        name: Necessity
        icon: /icon/guide/necessity.svg
        path: /guide/necessity/

      - text: 新生报到
        color: purple
        name: Check
        icon: /icon/guide/check.svg
        path: /guide/check/

      - text: 转专业
        color: olive
        name: Course
        icon: /icon/guide/degree.svg
        path: /guide/degree/

      - text: 课程
        color: mauve
        name: Course
        icon: /icon/guide/course.svg
        path: /guide/course/

      - text: 寝室
        color: blue
        name: Dorm
        icon: /icon/guide/dorm.svg
        path: /guide/dorm/

      - text: 食堂
        color: orange
        name: Dining
        icon: /icon/guide/dining.svg
        path: /guide/dining/
