title: 东师指南
id: guide
grey: true
hidden: true
content:
  - tag: grid
    header: 新生你好
    content:
      - text: 入学准备
        color: red
        name: Prepare
        icon: https://mp.innenu.com/img/icon/guide/prepare.svg
        path: guide/prepare/

      - text: 新生报到
        color: orange
        name: Check
        icon: /icon/guide/check.svg
        path: guide/check/

      - text: 需带物品
        color: blue
        name: Necessity
        icon: /icon/guide/necessity.svg
        path: guide/necessity/

      - text: 常见问题
        color: cyan
        name: FAQ
        icon: /icon/guide/faq.svg
        path: guide/faq/

  - tag: grid
    header: 学在东师
    content:
      - text: 学位
        color: blue
        name: Course
        icon: /icon/guide/degree.svg
        path: guide/degree/

      - text: 课程
        color: orange
        name: Course
        icon: /icon/guide/course.svg
        path: guide/course/

      - text: 学习
        color: red
        name: Study
        icon: /icon/guide/study.svg
        path: guide/study/

      - text: 选课
        color: purple
        name: Select
        icon: /icon/guide/select.svg
        path: guide/select/

      - text: 图书馆
        color: cyan
        name: Library
        icon: /icon/guide/library.svg
        path: /intro/apartment/library/

      - text: 考试
        color: olive
        name: Exam
        icon: /icon/guide/test.svg
        path: guide/exam/

  - tag: grid
    header: 行在东师
    content:
      - text: 寝室
        color: blue
        name: Dorm
        icon: /icon/guide/dorm.svg
        path: guide/dorm/

      - text: 食堂
        color: orange
        name: Dining
        icon: /icon/guide/dining.svg
        path: guide/dining/

      - text: 校园卡
        color: red
        name: Card
        icon: /icon/guide/card.svg
        path: guide/card/

      - text: 校园网
        color: purple
        name: Network
        icon: /icon/guide/network.svg
        path: guide/network/

      - text: 账户
        color: olive
        name: Account
        icon: /icon/guide/account.svg
        path: guide/account/

      - text: 生活
        color: mauve
        name: Life
        icon: /icon/guide/life.svg
        path: guide/life/

      - text: SIM 卡
        color: blue
        name: SIM
        icon: /icon/guide/sim.svg
        path: guide/sim/

      - text: 资助
        color: orange
        name: Subsidize
        icon: /icon/guide/subsidize.svg
        path: guide/subsidize/

  - tag: grid
    header: 乐在东师
    content:
      - text: 学生组织
        color: blue
        name: Orgnazation
        icon: /icon/guide/student-org.svg
        path: guide/organization/

      - text: 社团
        color: orange
        name: Association
        icon: /icon/guide/association.svg
        path: guide/association/

      - text: 交通
        color: red
        name: Traffic
        icon: /icon/guide/traffic.svg
        path: guide/traffic/

      - text: 吃喝玩乐
        color: purple
        name: Nearby
        icon: /icon/guide/nearby.svg
        path: guide/life/nearby/

    footer: " "
