- tag: list
  header: 工作室与开发者介绍
  content:
    - text: "   小程序全部内容均由 Hope Studio 独立开发。"
    - text: "   小程序现有字数为 306095 字，其中东师介绍部分 136523 字，东师指南部分 121299 字，功能大厅部分 29723 字，其他部分 18550 字。"
    - text: Hope Studio 介绍
      url: page?path=other/about/hope-studio

    - text: Mr.Hope 个人介绍
      url: page?path=other/about/mrhope

    - text: 致谢名单
      url: page?path=other/about/thanks
