title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    header: 使用必读
    content:
      - text: 小程序使用须知
        icon: /icon/about.svg
        url: page?path=other/about/guide

  - tag: list
    header: 新生入学课程
    content:
      - text: 新生入学课程教程
        icon: /icon/guide/study.svg
        path: /guide/prepare/yiban/

  - tag: grid
    header: 最常访问
    content:
      - text: 招生录取
        color: red
        name: Description
        icon: /icon/about.svg
        path: /intro/enroll/search

      - text: 入学准备
        color: orange
        name: Prepare
        icon: https://mp.innenu.com/img/icon/guide/prepare.svg
        path: /guide/prepare/

      - text: 需带物品
        color: blue
        name: Necessity
        icon: /icon/guide/necessity.svg
        path: /guide/necessity/

      - text: 新生报到
        color: purple
        name: Check
        icon: /icon/guide/check.svg
        path: /guide/check/

      - text: 转专业
        color: olive
        name: Course
        icon: /icon/guide/degree.svg
        path: /guide/degree/

      - text: 课程
        color: mauve
        name: Course
        icon: /icon/guide/course.svg
        path: /guide/course/

      - text: 寝室
        color: blue
        name: Dorm
        icon: /icon/guide/dorm.svg
        path: /guide/dorm/

      - text: 食堂
        color: orange
        name: Dining
        icon: /icon/guide/dining.svg
        path: /guide/dining/
