title: 功能大厅
id: function
grey: true
hidden: true
content:
  - tag: card
    type: page
    src: http://mp.innenu.com/img/tab/map.jpg
    title: 校园地图
    logo: /icon/function/map.svg
    base64Logo: map
    url: map

  - tag: card
    type: page
    src: http://mp.innenu.com/img/tab/headphone.jpg
    title: 音悦东师
    logo: /icon/function/music.svg
    base64Logo: music
    url: player

  - tag: card
    type: page
    src: http://mp.innenu.com/img/tab/calendar.jpg
    title: 校历
    logo: /icon/function/calendar.svg
    base64Logo: calendar
    url: calendar

  - tag: card
    type: page
    src: http://mp.innenu.com/img/tab/sport-field.jpg
    title: 体测计算器
    logo: /icon/function/calculate.svg
    base64Logo: calculate
    url: PEcal

  - tag: card
    type: page
    src: http://mp.innenu.com/img/tab/wechat.jpg
    title: 校园公众号
    logo: /icon/function/wechat.svg
    base64Logo: wechat
    url: wechat
