app:
  title: 欢迎使用 in 东师
  content: 欢迎使用 in 东师。这是一个由 Mr.Hope 个人制作的非官方小程序，内含 31 万字的新生攻略。希望大家能够通过小程序摆脱对大学的迷茫。
calendar:
  title: 放假日期
  content: |-
    本科为 1 月 16 日放假
  force: true
donate:
  title: 非法访问
  content: 腾讯禁止个人小程序放置任何收款方式。您不能访问本页面，本页面仅用于测试！
donate-list:
  title: 非法访问
  content: 腾讯禁止个人小程序放置任何收款方式。您不能访问本页面，本页面仅用于测试！
