title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    header: 新生报到
    content:
      - text: 大学第一天
        path: /guide/check/first-day

  - tag: grid
    header: 最常访问
    content:
      - text: 入学课程
        color: red
        name: Course
        icon: /icon/guide/study.svg
        base64Icon: study
        path: /guide/prepare/yiban/

      - text: 新生报到
        color: orange
        name: Check
        icon: /icon/guide/check.svg
        base64Icon: check
        path: /guide/check/

      - text: 入学活动
        color: blue
        name: Activity
        icon: https://mp.innenu.com/img/icon/guide/activity.svg
        base64Icon: activity
        path: guide/activity/

      - text: 校园卡
        color: purple
        name: Card
        icon: /icon/guide/card.svg
        base64Icon: card
        path: /guide/card/

      - text: 寝室
        color: mauve
        name: Dorm
        icon: /icon/guide/dorm.svg
        base64Icon: dorm
        path: /guide/dorm/

      - text: 食堂
        color: olive
        name: Dining
        icon: /icon/guide/dining.svg
        base64Icon: dining
        path: /guide/dining/

      - text: 校园网
        color: red
        name: Network
        icon: /icon/guide/network.svg
        base64Icon: network
        path: /guide/network/

      - text: 快递
        color: blue
        name: blue
        icon: https://mp.innenu.com/img/icon/guide/express.svg
        base64Icon: express
        path: /guide/express/

      - text: 超市
        color: orange
        name: Shop
        icon: https://mp.innenu.com/img/icon/guide/shop.svg
        base64Icon: shop
        path: /guide/shop/

      - text: 洗浴
        color: purple
        name: Bath
        icon: https://mp.innenu.com/img/icon/guide/bath.svg
        base64Icon: bath
        path: guide/bath/

      - text: 账户
        color: olive
        name: Account
        icon: /icon/guide/account.svg
        base64Icon: account
        path: guide/account/

  - tag: list
    header: 使用必读
    content:
      - text: 小程序使用须知
        icon: /icon/about.svg
        base64Icon: about
        url: page?path=other/about/guide

      - text: 常见问题及解答
        icon: /icon/guide/faq.svg
        base64Icon: faq
        path: /guide/faq/

  - tag: list
    header: 今日趣闻
    content:
      - text: 今天 Mr.Hope 遇到了一个有趣的人
        url: page?path=other/MrHope/interesting/index

      - text: 现状陈述
        desc: Mr.Hope の当前现状
        url: page?path=other/MrHope/cry

  - tag: text
    heading: " "
    text: "   如果您还有什么疑问，欢迎加入 in 东师咨询群 (1139044856) 进行咨询。\n   小程序都是 Mr.Hope 个人开发编写，现已花费 Mr.Hope 近 1800 小时，文字数量超过 31 万字，同时小程序服务器每年会产生开销。如果您觉得小程序很有帮助，欢迎您进行打赏。"
    style:
      color: "#888"
      font-size: 14px

  - tag: list
    header: false
    content:
      - text: 赞赏支持 Mr.Hope
        icon: /icon/user/donate.svg
        base64Icon: donate
        url: donate
    footer: " "
