title: 首页
id: main
grey: true
hidden: true
content:
  - tag: list
    header: 使用必读
    content:
      - text: 小程序使用须知
        icon: /icon/about.svg
        url: page?path=other/about/guide

  - tag: list
    header: 新生入学课程
    content:
      - text: 新生入学课程教程
        icon: /icon/guide/study.svg
        path: /guide/prepare/yiban/

  - tag: grid
    header: 最常访问
    content:
      - text: 招生录取
        color: red
        name: Description
        icon: /icon/about.svg
        path: /intro/enroll/search

      - text: 入学准备
        color: orange
        name: Prepare
        icon: /icon/guide/prepare.svg
        path: /guide/prepare/

      - text: 需带物品
        color: blue
        name: Necessity
        icon: /icon/guide/necessity.svg
        path: /guide/necessity/

      - text: 新生报到
        color: purple
        name: Check
        icon: /icon/guide/check.svg
        path: /guide/check/

      - text: 转专业
        color: olive
        name: Course
        icon: /icon/guide/degree.svg
        path: /guide/degree/

      - text: 课程
        color: mauve
        name: Course
        icon: /icon/guide/course.svg
        path: /guide/course/

      - text: 寝室
        color: blue
        name: Dorm
        icon: /icon/guide/dorm.svg
        path: /guide/dorm/

      - text: 食堂
        color: orange
        name: Dining
        icon: /icon/guide/dining.svg
        path: /guide/dining/

  - tag: list
    header: 常见问题
    content:
      - text: 常见问题及解答
        icon: /icon/guide/faq.svg
        path: /guide/faq/

  - tag: list
    header: 今日趣闻
    content:
      - text: 今天 Mr.Hope 遇到了一个有趣的人
        url: page?path=other/MrHope/interesting/index

      - text: 现状陈述
        desc: Mr.Hope の当前现状
        url: page?path=other/MrHope/cry

  - tag: text
    heading: " "
    text: "   如果您还有什么疑问，欢迎加入 in 东师咨询群 (1139044856) 进行咨询。\n   小程序都是 Mr.Hope 个人开发编写，现已花费 Mr.Hope 近 1800 小时，文字数量超过 31 万字，同时小程序服务器每年会产生开销。如果您觉得小程序很有帮助，欢迎您进行打赏。"
    style:
      color: "#888"
      font-size: 14px

  - tag: list
    content:
      - text: 赞赏支持 Mr.Hope
        icon: /icon/user/donate.svg
        url: donate
    footer: " "
