title: 首页
id: main
grey: true
hidden: true
content:
  - tag: title
    text: Mr.Hope 强烈推荐

  - tag: card
    type: web
    src: http://mmbiz.qpic.cn/mmbiz_jpg/s67UCDghNJlEPh1vnuZzeniaj13zwQpJKeA1G28LhRlupVvyKqTdq4ico5NxnMFSFiaYtJgnicnrwI1ZJnOOLx5OHQ/0?wx_fmt=jpeg
    url: https://mp.weixin.qq.com/s/7pUqMhyIzlqoJD_4R0LXvg
    title: 纳新 | 青春遇见梦想，你我刚好在场
    desc: 校会君期待着你的到来
    logo: https://mp.innenu.com/img/nenuyouth.png
    name: 东师青年

  - tag: list
    header: 更多内容
    content:
      - text: 东师青年精彩推送
        url: /function/wechat/detail?path=nenuyouth

  - tag: grid
    header: 最常访问
    content:
      - text: 入学活动
        color: blue
        name: Activity
        icon: activity
        base64Icon: activity
        path: guide/activity/

      - text: 校园卡
        color: purple
        name: Card
        icon: card
        base64Icon: card
        path: /guide/card/

      - text: 寝室
        color: mauve
        name: Dorm
        icon: dorm
        base64Icon: dorm
        path: /guide/dorm/

      - text: 食堂
        color: olive
        name: Dining
        icon: dining
        base64Icon: dining
        path: /guide/dining/

      - text: 校园网
        color: red
        name: Network
        icon: network
        base64Icon: network
        path: /guide/network/

      - text: 快递
        color: blue
        name: blue
        icon: express
        base64Icon: express
        path: /guide/express/

      - text: 超市
        color: orange
        name: Shop
        icon: shop
        base64Icon: shop
        path: /guide/shop/

      - text: 洗浴
        color: purple
        name: Bath
        icon: bath
        base64Icon: bath
        path: guide/bath/

      - text: 账户
        color: olive
        name: Account
        icon: account
        base64Icon: account
        path: guide/account/

  - tag: list
    header: 使用必读
    content:
      - text: 小程序使用须知
        icon: about
        base64Icon: about
        url: page?path=other/about/guide

      - text: 常见问题及解答
        icon: faq
        base64Icon: faq
        path: /guide/faq/

  - tag: list
    header: 今日趣闻
    content:
      - text: 今天 Mr.Hope 遇到了一个有趣的人
        url: page?path=other/MrHope/interesting/index

      - text: 现状陈述
        desc: Mr.Hope の当前现状
        url: page?path=other/MrHope/cry

  - tag: text
    heading: " "
    text: "   如果您还有什么疑问，欢迎加入 in 东师咨询群 (1139044856) 进行咨询。\n   小程序都是 Mr.Hope 个人开发编写，现已花费 Mr.Hope 近 1800 小时，文字数量超过 31 万字，同时小程序服务器每年会产生开销。如果您觉得小程序很有帮助，欢迎您进行打赏。"
    style:
      color: "#888"
      font-size: 14px

  - tag: list
    header: false
    content:
      - text: 赞赏支持 Mr.Hope
        icon: donate
        base64Icon: donate
        url: donate
    footer: " "
